extends SceneTree
## Render the gardener portrait while preserving authored portraits for Q, Alan, and Taibo.

func _initialize() -> void:
	call_deferred("run")

func run() -> void:
	var dialogue_assets_only := "--dialogue-assets-only" in OS.get_cmdline_user_args()
	var viewport := SubViewport.new()
	viewport.size = Vector2i(384, 512) if dialogue_assets_only else Vector2i(192, 192)
	viewport.transparent_bg = true
	viewport.render_target_update_mode = SubViewport.UPDATE_ALWAYS
	root.add_child(viewport)
	var world := Node3D.new()
	viewport.add_child(world)
	var env := WorldEnvironment.new()
	env.environment = Environment.new()
	env.environment.background_mode = Environment.BG_CLEAR_COLOR
	env.environment.ambient_light_source = Environment.AMBIENT_SOURCE_COLOR
	env.environment.ambient_light_color = Color.WHITE
	env.environment.ambient_light_energy = .7
	world.add_child(env)
	var sun := DirectionalLight3D.new()
	sun.rotation_degrees = Vector3(-35, -30, 0)
	world.add_child(sun)
	var camera := Camera3D.new()
	camera.projection = Camera3D.PROJECTION_ORTHOGONAL
	camera.size = 1.8
	world.add_child(camera)
	camera.position = Vector3(0, 1.65, 4)
	camera.look_at(Vector3(0, 1.25, 0))
	var portraits := {}
	portraits["coder"] = "/agent-isles/brand/q-portrait.png"
	portraits["coordinator"] = "/agent-isles/brand/teacher-portrait.png"
	portraits["teacher"] = "/agent-isles/brand/teacher-portrait.png"
	portraits["file_keeper"] = "/agent-isles/brand/file-keeper-portrait.png"
	var ids := ["gardener"] if dialogue_assets_only else []
	for id in ids:
		var model_name := "npc_gardener"
		camera.size = 2.7 if dialogue_assets_only else 1.8
		camera.position = Vector3(0, 1.4, 4) if dialogue_assets_only else Vector3(0, 1.65, 4)
		camera.look_at(Vector3(0, 1.2, 0) if dialogue_assets_only else Vector3(0, 1.25, 0))
		var model := load("res://assets/" + model_name + ".glb").instantiate() as Node3D
		world.add_child(model)
		await process_frame
		await RenderingServer.frame_post_draw
		await process_frame
		await RenderingServer.frame_post_draw
		var image := viewport.get_texture().get_image()
		if dialogue_assets_only:
			image.save_png("res://assets/portraits/%s.png" % id)
		else:
			portraits[id] = "data:image/webp;base64," + Marshalls.raw_to_base64(image.save_webp_to_buffer(false, .8))
		model.queue_free()
		await process_frame
	if dialogue_assets_only:
		print("DIALOGUE_PORTRAITS_COMPLETE")
		quit()
		return
	var output := FileAccess.open("res://../../packages/agent-isles-web/src/client/resident-portraits.ts", FileAccess.WRITE)
	output.store_string("// Generated by games/mosslight/tools/render_resident_portraits.gd; Q, Alan, and Taibo use authored illustrations.\nexport const RESIDENT_PORTRAITS = " + JSON.stringify(portraits, "  ") + " as const\n")
	output.close()
	print("RESIDENT_PORTRAITS_COMPLETE")
	quit()
