import { useEffect, useRef, useState } from 'react'
import type { Capture, FeedbackDraft, Annotation } from '../../projects/metadata.js'
import type { AgentIslesWorldInjected } from '../AgentIslesWorld.js'
import { api, command, mediaUrl } from './api.js'
import { imageElement, pngUpload, thumbnail } from './capture.js'
import { translator, errorText } from './words.js'
export interface CaptureInput {dataUrl:string;id?:string;previewId?:string;versionId?:string;source:'preview'|'upload';cover?:boolean;capturedAt?:number}
interface EditorFrame {base:string;marks:Annotation[]}
export interface EditorMemory {base:string;marks:Annotation[];text:string;route:string;revision:number;captureId?:string;requestId?:string;delivery?:FeedbackDraft['delivery'];uploaded:boolean;textOnly:boolean;imageSupport:boolean;target:boolean;origin?:CaptureInput;history?:EditorFrame[];future?:EditorFrame[];zoom?:number}
export function FeedbackPanel({projectId,sessionId,en,input,saved,captures,coverRevision,busy,send,refresh,done,restore,memory,remember,acknowledge}:{acknowledge(draft:FeedbackDraft,base:string,origin?:CaptureInput):void;memory?:EditorMemory;remember(value:EditorMemory):void;projectId:string;sessionId:string;en:boolean;input?:CaptureInput;saved?:FeedbackDraft;captures:Record<string,Capture>;coverRevision:number;busy:boolean;send:NonNullable<AgentIslesWorldInjected['sendProjectFeedback']>;refresh():Promise<void>;done():void;restore(versionId:string):Promise<void>}) {
  const t=translator(en),[base,setBase]=useState(memory?.base??input?.dataUrl??''),[marks,setMarks]=useState<Annotation[]>(memory?.marks??(input?[]:saved?.annotations)??[]),[text,setText]=useState(memory?.text??saved?.text??''),[route,setRoute]=useState(memory?.route??saved?.route??''),[revision,setRevision]=useState(memory?.revision??saved?.revision??0)
  const [captureId,setCaptureId]=useState(memory?.captureId??(input?undefined:saved?.captureId)),[mode,setMode]=useState<'rect'|'redact'|'crop'>(input?.cover?'crop':'rect'),[error,setError]=useState(''),[working,setWorking]=useState(false),[status,setStatus]=useState(''),[textOnly,setTextOnly]=useState(memory?.textOnly??true),[imageSupport,setImageSupport]=useState(memory?.imageSupport??false),[target,setTarget]=useState(memory?.target??false),[requestId,setRequestId]=useState(memory?.requestId??saved?.requestId),[delivery,setDelivery]=useState(memory?.delivery??saved?.delivery),[uploaded,setUploaded]=useState(memory?.uploaded??false)
  const [history,setHistory]=useState<EditorFrame[]>(memory?.history??[]),[future,setFuture]=useState<EditorFrame[]>(memory?.future??[]),[zoom,setZoom]=useState(memory?.zoom??100),[drag,setDrag]=useState<{x:number;y:number;w:number;h:number}>(),start=useRef<{x:number;y:number}>(),area=useRef<HTMLDivElement>(null),sendLock=useRef(false),workLock=useRef(false)
  const [origin,setOrigin]=useState<CaptureInput|undefined>(input??memory?.origin??(saved&&captures[saved.captureId]?{...captures[saved.captureId]!,dataUrl:''}:undefined))
  const meta=uploaded?{source:'upload' as const,versionId:undefined}:(origin??captures[captureId??'']),cover=!!origin?.cover
  useEffect(()=>{remember({base,marks,text,route,revision,captureId,requestId,delivery,uploaded,textOnly,imageSupport,target,origin,history,future,zoom})},[base,marks,text,route,revision,captureId,requestId,delivery,uploaded,textOnly,imageSupport,target,origin,history,future,zoom])
  // An acknowledged write can arrive after this panel closed and reopened.
  // Adopt only metadata from our own local memory; never replace newer editor input.
  useEffect(()=>{if(memory && memory.revision>revision){setRevision(memory.revision);setCaptureId(memory.captureId);setOrigin(memory.origin);setRequestId(memory.requestId);setDelivery(memory.delivery)}},[memory?.revision])
  useEffect(()=>{if(base||!captureId)return;let active=true;void mediaUrl(projectId,captures[captureId]?.hash??'').then(url=>{if(active)setBase(url)}).catch(e=>setError(errorText(e,en)));return()=>{active=false}},[])
  useEffect(()=>{const paste=(e:ClipboardEvent)=>{const file=Array.from(e.clipboardData?.files??[]).find(f=>f.type.startsWith('image/'));if(file&&!cover&&!requestId){e.preventDefault();void upload(file)}};window.addEventListener('paste',paste);return()=>window.removeEventListener('paste',paste)},[cover,requestId])
  async function run(fn:()=>Promise<void>){if(workLock.current)return;workLock.current=true;setWorking(true);setError('');setStatus('');try{await fn()}catch(e){setError(errorText(e,en))}finally{workLock.current=false;setWorking(false)}}
  function checkpoint(){setHistory(h=>[...h.slice(-19),{base,marks:structuredClone(marks)}]);setFuture([])}
  function applyFrame(frame:EditorFrame){setBase(frame.base);setMarks(structuredClone(frame.marks));setCaptureId(undefined)}
  function undo(){const frame=history.at(-1);if(frame){setFuture(f=>[...f,{base,marks:structuredClone(marks)}]);setHistory(history.slice(0,-1));applyFrame(frame)}}
  function redo(){const frame=future.at(-1);if(frame){setHistory(h=>[...h,{base,marks:structuredClone(marks)}]);setFuture(future.slice(0,-1));applyFrame(frame)}}
  async function upload(file:File){await run(async()=>{setBase(await pngUpload(file));setUploaded(true);setCaptureId(undefined);setMarks([]);setHistory([]);setFuture([])})}
  function position(e:React.PointerEvent){const r=area.current!.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))}}
  function down(e:React.PointerEvent<HTMLDivElement>){if(working||requestId)return;start.current=position(e);e.currentTarget.setPointerCapture(e.pointerId);setDrag({...start.current,w:0,h:0})}
  function move(e:React.PointerEvent){if(!start.current)return;const p=position(e),a=start.current;setDrag({x:Math.min(a.x,p.x),y:Math.min(a.y,p.y),w:Math.abs(p.x-a.x),h:Math.abs(p.y-a.y)})}
  async function up(){start.current=undefined;const r=drag;setDrag(undefined);if(!r||r.w<.005||r.h<.005)return;if(mode==='rect'){if(marks.length<12){checkpoint();setMarks([...marks,{...r,text:''}])}return}
    await run(async()=>{const img=await imageElement(base),c=document.createElement('canvas');c.width=mode==='crop'?Math.max(1,Math.round(img.width*r.w)):img.width;c.height=mode==='crop'?Math.max(1,Math.round(img.height*r.h)):img.height;const g=c.getContext('2d')!;if(mode==='crop'){g.drawImage(img,img.width*r.x,img.height*r.y,img.width*r.w,img.height*r.h,0,0,c.width,c.height);setMarks([])}else{g.drawImage(img,0,0);g.fillStyle='#111';g.fillRect(Math.floor(img.width*r.x),Math.floor(img.height*r.y),Math.ceil(img.width*r.w)+1,Math.ceil(img.height*r.h)+1)}checkpoint();setBase(c.toDataURL('image/png'));setCaptureId(undefined)})
  }
  async function persist():Promise<FeedbackDraft>{
    let id=captureId, persistedOrigin=origin
    if(!id){if(!base)throw new Error('invalid-media');const source=uploaded?'upload':origin?.source??'upload';const c=await command<Capture>({op:'media-save',projectId,sessionId,source,derivedFrom:uploaded?undefined:origin?.id,previewId:uploaded?undefined:origin?.previewId,versionId:uploaded?undefined:origin?.versionId,capturedAt:uploaded?undefined:origin?.capturedAt,data:base.split(',')[1],thumbnail:await thumbnail(base)});id=c.id;persistedOrigin={...c,dataUrl:''};setCaptureId(id);setOrigin(persistedOrigin)}
    const d=await command<FeedbackDraft>({op:'feedback-save',projectId,revision,draft:{sessionId,captureId:id,text,route,annotations:marks,requestId,delivery}});acknowledge(d,base,persistedOrigin);setRevision(d.revision);return d
  }
  async function sendFeedback(){
    if(sendLock.current)return;sendLock.current=true
    try{
      let d=await persist()
      if(d.requestId){const check=await api<{accepted:boolean}>('submission',projectId,{session:sessionId,request:d.requestId});if(check.accepted){await command({op:'feedback-delete',projectId,sessionId,revision:d.revision});done();return}}
      const provenance=captures[d.captureId]??meta
      let message=`${text}\n\n${t('feedbackSource')}: ${provenance?.source==='preview'?t('previewCapture'):t('uploaded')}\nProject: ${projectId}\nVersion: ${provenance?.versionId??'current files'}\n${route?`User-provided route: ${route}\n`:''}${marks.map((a,i)=>`${i+1}. ${a.text} [x=${a.x.toFixed(3)}, y=${a.y.toFixed(3)}, w=${a.w.toFixed(3)}, h=${a.h.toFixed(3)}]`).join('\n')}\n${t('oldCapture')}`
      let picture:string|undefined
      if(!textOnly){if(!imageSupport)throw new Error('imageHint');const img=await imageElement(base),c=document.createElement('canvas');c.width=img.width;c.height=img.height;const g=c.getContext('2d')!;g.drawImage(img,0,0);marks.forEach((a,i)=>{g.strokeStyle='#c24f26';g.lineWidth=Math.max(3,c.width/400);g.strokeRect(a.x*c.width,a.y*c.height,a.w*c.width,a.h*c.height);g.fillStyle='#c24f26';g.fillRect(a.x*c.width,a.y*c.height,30,30);g.fillStyle='white';g.font='bold 20px sans-serif';g.fillText(String(i+1),a.x*c.width+6,a.y*c.height+23)});picture=c.toDataURL('image/png').split(',')[1]}
      let frozen=d.delivery
      if(frozen){message=frozen.text;picture=frozen.imageCaptureId?(await mediaUrl(projectId,(await api<{captures:Record<string,Capture>}>('state',projectId)).captures[frozen.imageCaptureId]!.hash)).split(',')[1]:undefined}
      else {
        const imageCapture=picture?await command<Capture>({op:'media-save',projectId,sessionId,source:'upload',data:picture}):undefined
        frozen={text:message,imageCaptureId:imageCapture?.id}
      }
      await send(projectId,sessionId,message,picture,d.requestId,async id=>{d=await command<FeedbackDraft>({op:'feedback-save',projectId,revision:d.revision,draft:{...d,requestId:id,delivery:frozen}});acknowledge(d,base,origin);setRevision(d.revision);setRequestId(id);setDelivery(frozen)})
      await command({op:'feedback-delete',projectId,sessionId,revision:d.revision});await refresh();done()
    }finally{sendLock.current=false}
  }
  return <section>{!cover&&(saved?.revision??0)!==revision&&<div role="alert"><p>{t('feedbackConflict')}</p><button disabled={working} onClick={()=>void run(async()=>{const latest=await api<{feedback:Record<string,FeedbackDraft>;captures:Record<string,Capture>}>('state',projectId);const d=latest.feedback[sessionId];if(!d){setRevision(0);setRequestId(undefined);setDelivery(undefined);return}const c=latest.captures[d.captureId]!;setBase(await mediaUrl(projectId,c.hash));setOrigin({...c,dataUrl:''});setUploaded(c.source==='upload');setCaptureId(c.id);setMarks(d.annotations);setText(d.text);setRoute(d.route??'');setRevision(d.revision);setRequestId(d.requestId);setDelivery(d.delivery);setHistory([]);setFuture([])})}>{t('reloadFeedback')}</button></div>}<p className="ci-dialogue-line">{cover?t('coverHint'):t('annotateGuide')}</p>
    {!cover&&<details open={!base}><summary>{t(base?'replaceImage':'uploadScreenshot')}</summary><label>{t('uploadScreenshot')}<input disabled={working||!!requestId} type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/></label></details>}
    {base&&<><div className="ci-actions">{(['rect','redact','crop'] as const).filter(v=>!cover||v!=='rect').map(m=><button key={m} aria-pressed={mode===m} disabled={working||!!requestId} onClick={()=>setMode(m)}>{t(m)}</button>)}<button disabled={!history.length||working||!!requestId} onClick={undo}>{t('undo')}</button><button disabled={!future.length||working||!!requestId} onClick={redo}>{t('redo')}</button></div>
      <details><summary>{t('imageTools')}</summary><label>{t('zoom')}<input type="range" min="100" max="300" step="25" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/>{zoom}%</label></details><p className="ci-muted">{t('currentTool')}: {t(mode)} · {t('drawGuide')}</p><div className="ci-annotation-scroll"><div ref={area} style={{width:`${zoom}%`}} className="ci-annotation-image" onPointerDown={down} onPointerMove={move} onPointerUp={()=>void up()} onPointerCancel={()=>{start.current=undefined;setDrag(undefined)}}><img src={base} alt={t('feedbackSource')} draggable={false}/>{marks.map((a,i)=><span key={i} className="ci-box" style={{left:`${a.x*100}%`,top:`${a.y*100}%`,width:`${a.w*100}%`,height:`${a.h*100}%`}}>{i+1}</span>)}{drag&&<span className="ci-box" style={{left:`${drag.x*100}%`,top:`${drag.y*100}%`,width:`${drag.w*100}%`,height:`${drag.h*100}%`}}/>}</div></div></>}
    {!cover&&<><div className="ci-list">{marks.map((a,i)=><label key={i}>{i+1}.<input disabled={!!requestId} maxLength={1000} value={a.text} onFocus={checkpoint} onChange={e=>setMarks(marks.map((v,j)=>i===j?{...v,text:e.target.value}:v))}/><button disabled={!!requestId} onClick={()=>{checkpoint();setMarks(marks.filter((_,j)=>j!==i))}}>{t('deleteAnnotation')}</button></label>)}</div><label>{t('feedbackText')}<textarea disabled={!!requestId} value={text} maxLength={6000} onChange={e=>setText(e.target.value)}/></label><details><summary>{t('feedbackDelivery')}</summary><label>{t('feedbackRoute')}<input disabled={!!requestId} value={route} maxLength={300} onChange={e=>setRoute(e.target.value)}/></label>{meta&&<p className="ci-muted">{t('feedbackSource')}: {meta.source==='preview'?t('previewCapture'):t('uploaded')} · {meta.versionId?.slice(0,8)??t('current')}</p>}<p className="ci-muted">{t('draftHint')}</p></details>
    {meta?.versionId&&<><p>{t('feedbackHistorical')}</p><label className="ci-check"><input type="checkbox" checked={target} onChange={e=>setTarget(e.target.checked)}/>{t('editCurrent')}</label><button disabled={working} onClick={()=>void run(()=>restore(meta.versionId!))}>{t('restoreFeedback')}</button></>}
    {textOnly&&<p className="ci-muted">{t('feedbackTextMode')}</p>}<details><summary>{t('feedbackOptions')}</summary><p className="ci-muted">{t('imageHint')}</p><label className="ci-check"><input type="checkbox" disabled={!!requestId} checked={textOnly} onChange={e=>setTextOnly(e.target.checked)}/>{t('textOnly')}</label>{!textOnly&&<label className="ci-check"><input disabled={!!requestId} type="checkbox" checked={imageSupport} onChange={e=>setImageSupport(e.target.checked)}/>{t('imageSupport')}</label>}</details>
    {requestId&&<p role="status">{t('unknownSubmission')}</p>}<div className="ci-actions"><button disabled={working||!base||!!requestId} onClick={()=>void run(async()=>{await persist();await refresh();setStatus(t('draftSaved'))})}>{t('saveDraft')}</button><button className="ci-primary" disabled={working||busy||!base||(!text.trim()&&!marks.some(m=>m.text.trim()))||(!textOnly&&!imageSupport)||(!!meta?.versionId&&!target)} onClick={()=>void run(sendFeedback)}>{t(textOnly?'sendTextFeedback':'sendFeedback')}</button><button disabled={working||!!requestId} onClick={()=>void run(async()=>{if(saved||captureId)await command({op:'feedback-delete',projectId,sessionId,revision});await refresh();done()})}>{t('discardDraft')}</button></div></>}
    {cover&&<button className="ci-primary" disabled={working||!base} onClick={()=>void run(async()=>{const c=await command<Capture>({op:'media-save',projectId,sessionId,source:'preview',previewId:origin!.previewId,versionId:origin!.versionId,capturedAt:origin!.capturedAt,data:base.split(',')[1],thumbnail:await thumbnail(base)});await command({op:'cover-set',projectId,versionId:origin!.versionId,captureId:c.id,revision:coverRevision,confirmed:true});await refresh();setStatus(t('coverSaved'));done()})}>{t('confirmCover')}</button>}
    {status&&<p role="status">{status}</p>}{error&&<p role="alert" className="ci-error">{error}</p>}
  </section>
}
