export const islandStyles = `
.ci-island{position:absolute;inset:0;color:#24352f;font:15px/1.5 -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#c5ddd2;pointer-events:auto}
.ci-island *{box-sizing:border-box}.ci-island button,.ci-island input,.ci-island textarea,.ci-island select{font:inherit}.ci-island button{border:1px solid #bdc9c1;border-radius:10px;padding:9px 13px;background:#fffdf7;color:#24352f;cursor:pointer;min-height:40px}.ci-island button:hover{background:#e7eee6}.ci-island button:disabled{opacity:.5;cursor:wait}.ci-island button:focus-visible,.ci-island input:focus-visible,.ci-island textarea:focus-visible{outline:3px solid #c86b42;outline-offset:2px}.ci-island a{color:#22675b}
.ci-world{position:absolute;inset:0;width:100%;height:100%;border:0}.ci-top{position:absolute;inset:16px 20px auto;display:flex;gap:8px;justify-content:space-between;z-index:6;pointer-events:none}.ci-top>div{display:flex;gap:8px;min-width:0}.ci-top button{pointer-events:auto;box-shadow:0 3px 14px #17392c18;max-width:42vw;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.ci-nav{position:absolute;bottom:22px;left:50%;transform:translateX(-50%);display:flex;gap:8px;padding:8px;border-radius:18px;background:#f7f6f2ee;box-shadow:0 8px 28px #203c3722;z-index:6;width:max-content;max-width:95vw}.ci-nav button{border:0;background:transparent}.ci-nav button:first-child{background:#22675b;color:white}
.ci-welcome{position:absolute;top:90px;left:24px;max-width:310px;background:#f7f6f2e8;padding:16px 20px;border-radius:12px;z-index:5}.ci-welcome h1{font-size:22px;margin:0 0 8px}.ci-welcome p{margin:0 0 12px}.ci-light{position:absolute;inset:100px 5% 120px;display:flex;align-items:center;justify-content:center;gap:24px;flex-wrap:wrap}.ci-light button{display:grid;gap:12px;justify-items:center}.ci-light img{width:100px;height:100px;object-fit:contain}
.ci-panel{position:absolute;top:76px;right:20px;bottom:98px;width:min(520px,42vw);min-width:380px;background:#f7f6f2;border:1px solid #becdc3;border-radius:18px;box-shadow:0 14px 48px #183a3930;z-index:20;display:flex;flex-direction:column;overflow:hidden}.ci-panel.wide{width:min(1060px,85vw)}.ci-panel.focus{inset:8px;width:auto;min-width:0;z-index:30}.ci-panel>header{display:flex;gap:10px;align-items:center;padding:12px 16px;border-bottom:1px solid #dce1db;flex:none}.ci-panel>header img{width:42px;height:48px;object-fit:contain}.ci-panel>header div{flex:1;min-width:0}.ci-panel>header strong,.ci-panel>header small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.ci-panel>header small{font-size:12px;color:#596b60}.ci-body{padding:18px;overflow:auto;min-height:0;flex:1}.ci-body h2{font-size:20px}.ci-body h3{font-size:16px}.ci-body input,.ci-body textarea,.ci-body select{width:100%;padding:10px;border:1px solid #acbfb2;border-radius:8px;background:white;color:#24352f}.ci-body label{display:grid;gap:6px;margin:12px 0}.ci-body textarea{min-height:100px}.ci-actions{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}.ci-primary{background:#22675b!important;color:white!important}.ci-list{display:grid;gap:10px}.ci-item{padding:14px;background:white;border:1px solid #dce1db;border-radius:12px}.ci-item p{margin:6px 0}.ci-muted{font-size:13px;color:#596b60;overflow-wrap:anywhere}.ci-error{padding:10px;background:#ffebe4;border-left:3px solid #a44528;overflow-wrap:anywhere}.ci-status{padding:8px 14px;background:#e8eee4;display:flex;gap:8px;align-items:center;font-size:13px;flex:none}.ci-status span{flex:1}.ci-panel .town-native-chat-seat{flex:1;min-height:150px;width:100%;position:relative}.ci-chat-tools{padding:8px 12px;display:flex;gap:6px;flex-wrap:wrap;flex:none}.ci-chat-tools button{padding:6px 10px;font-size:13px}.ci-preview{width:100%;height:55vh;border:1px solid #c6d2c9;background:white;border-radius:8px}.ci-code{white-space:pre-wrap;overflow-wrap:anywhere;background:#edf1eb;padding:12px;font:12px/1.6 ui-monospace,monospace;max-height:50vh;overflow:auto}.ci-diff{display:grid;grid-template-columns:1fr 1fr;gap:12px}.ci-image{max-width:100%;max-height:60vh;object-fit:contain}.ci-gallery{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.ci-version-icon{background:#e2eade;border-radius:8px;padding:24px;font-size:30px;color:#22675b;text-align:center}.ci-notice{position:absolute;left:20px;bottom:105px;padding:12px;background:#fffdf7;max-width:300px;border-radius:10px;z-index:25}.ci-island .town-panel{z-index:40}.ci-island pre{margin:8px 0}
@media(max-width:800px){.ci-panel,.ci-panel.wide{inset:70px 8px 88px;width:auto;min-width:0}.ci-top{inset:10px 8px auto;gap:4px}.ci-top button{font-size:12px;padding:7px}.ci-nav{bottom:10px;gap:0;padding:4px;flex-wrap:wrap;justify-content:center}.ci-nav button{font-size:12px;padding:6px 9px}.ci-welcome{top:85px;left:12px;max-width:280px}.ci-diff{grid-template-columns:1fr}.ci-panel>header{padding:10px;gap:6px}.ci-panel>header button{font-size:12px;padding:5px 8px}.ci-body{padding:12px}.ci-gallery{grid-template-columns:1fr}}
@media(prefers-reduced-motion:reduce){.ci-island *{animation:none!important;transition:none!important}}
`
